# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthservice',
            name='authorization_endpoint',
        ),
        migrations.RemoveField(
            model_name='oauthservice',
            name='token_endpoint',
        ),
        migrations.AlterField(
            model_name='oauthservice',
            name='name',
            field=models.CharField(choices=[('microsoft', 'Microsoft')], max_length=250, verbose_name='identifiant'),
        ),
    ]
