# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170101_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtoken',
            name='uuid',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='auth_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
