# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170101_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='auth_token',
            field=models.TextField(),
        ),
    ]
